# Generated by Django 5.1.4 on 2025-01-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='title',
            new_name='courseName',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='instructor_name',
            new_name='instructorName',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='start_date',
        ),
    ]
