# Generated by Django 5.1.4 on 2025-01-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_title_courses_coursename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
