# Generated by Django 5.1.4 on 2025-01-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_title',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
